elements = {
    "fire" : {
        "mask" : {
            "name" : "Ultimate shield",
            "shield" : 15,
            "damage" : 0,
            "attack" : 0,
            "energy" : -20,
            "health" : 0,
        },
        "normal" : {
            "name" : "Raging Flame",
            "shield" : 0,
            "damage" : 0,
            "attack" : -15,
            "energy" : -17,
            "health" : 0,
        },
        "heal" : {
            "name" : "Protodermis tea",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : -12,
            "health" : 10,
        },
        "rest" : {
            "name" : "Lava bath",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : 15,
            "health" : 0,
        },
    },

"water" : {
        "mask" : {
            "name" : "Deep dive",
            "shield" : 12,
            "damage" : 0,
            "attack" : 0,
            "energy" : -22,
            "health" : 0,
        },
        "normal" : {
            "name" : "Waterfall",
            "shield" : 0,
            "damage" : 0,
            "attack" : -15,
            "energy" : -14,
            "health" : 0,
        },
        "heal" : {
            "name" : "Protodermis tea",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : -10,
            "health" : 10,
        },
        "rest" : {
            "name" : "Kini-Nui meditation",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : 13,
            "health" : 0,
        },
    },

"earth" : {
        "mask" : {
            "name" : "Atlas",
            "shield" : 0,
            "damage" : 15,
            "attack" : 0,
            "energy" : -25,
            "health" : 0,
        },
        "normal" : {
            "name" : "Earthquake",
            "shield" : 0,
            "damage" : 0,
            "attack" : -20,
            "energy" : -22,
            "health" : 0,
        },
        "heal" : {
            "name" : "Protodermis tea",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : -15,
            "health" : 10,
        },
        "rest" : {
            "name" : "Mining",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : 18,
            "health" : 0,
        },
    },

"stone" : {
        "mask" : {
            "name" : "Speed of light",
            "shield" : 5,
            "damage" : 7,
            "attack" : 0,
            "energy" : -23,
            "health" : 0,
        },
        "normal" : {
            "name" : "Stone peaks",
            "shield" : 0,
            "damage" : 0,
            "attack" : -15,
            "energy" : -20,
            "health" : 0,
        },
        "heal" : {
            "name" : "Protodermis tea",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : -12,
            "health" : 12,
        },
        "rest" : {
            "name" : "Stone ball",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : 17,
            "health" : 0,
        },
    },

"air" : {
        "mask" : {
            "name" : "Levitation",
            "shield" : 13,
            "damage" : 0,
            "attack" : 0,
            "energy" : -20,
            "health" : 0,
        },
        "normal" : {
            "name" : "Tornado",
            "shield" : 0,
            "damage" : 0,
            "attack" : -17,
            "energy" : -25,
            "health" : 0,
        },
        "heal" : {
            "name" : "Protodermis tea",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : -10,
            "health" : 15,
        },
        "rest" : {
            "name" : "Lava bath",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : 19,
            "health" : 0,
        },
    },

"ice" : {
        "mask" : {
            "name" : "Eagle eye",
            "shield" : 8,
            "damage" : 5,
            "attack" : 0,
            "energy" : -22,
            "health" : 0,
        },
        "normal" : {
            "name" : "Absolute zero",
            "shield" : 0,
            "damage" : 0,
            "attack" : -18,
            "energy" : -24,
            "health" : 0,
        },
        "heal" : {
            "name" : "Protodermis tea",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : -12,
            "health" : 10,
        },
        "rest" : {
            "name" : "Snowman",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : 18,
            "health" : 0,
        },
    }
}