elements = {
    "fire" : {
        "mask" : {
            "name" : "Ultimate shield",
            "shield" : 14,
            "damage" : 0,
            "attack" : 0,
            "energy" : -24,
            "health" : 0,
            "description": "Creates shield around the user, reducing the damage received",
        },
        "normal" : {
            "name" : "Raging Flame",
            "shield" : 0,
            "damage" : 3,
            "attack" : -21,
            "energy" : -23,
            "health" : 0,
            "description": "Burns the opponent. Leaves scorches that deal additional damage during the next attack",
        },
        "heal" : {
            "name" : "Protodermis tea",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : -13,
            "health" : 11,
            "description": "A warm protodermis tea is a great way to recover",
        },
        "rest" : {
            "name" : "Lava bath",
            "shield" : 0,
            "damage" : 4,
            "attack" : 0,
            "energy" : 14,
            "health" : 0,
            "description": "Takes a lava bath. Deals more damage on attack due to being hot",
        },
    },

"water" : {
        "mask" : {
            "name" : "Deep dive",
            "shield" : 8,
            "damage" : 0,
            "attack" : 0,
            "energy" : -26,
            "health" : 5,
            "description": "Allows to dive deep into the water, dodging attacks. Water has healing effect on user",
        },
        "normal" : {
            "name" : "Tsunami",
            "shield" : 4,
            "damage" : 0,
            "attack" : -25,
            "energy" : -21,
            "health" : 0,
            "description": "Casts a tsunami wave over the opponent. The water also protects the user, reducing the damage from next attack",
        },
        "heal" : {
            "name" : "Protodermis tea",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : -15,
            "health" : 15,
            "description": "A warm protodermis tea is a great way to recover",
        },
        "rest" : {
            "name" : "Kini-Nui meditation",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : 12,
            "health" : 3,
            "description": "Kini-Nui meditation. replenishes one's stamina and health",
        },
    },

"earth" : {
        "mask" : {
            "name" : "Atlas",
            "shield" : 0,
            "damage" : 11,
            "attack" : -10,
            "energy" : -26,
            "health" : 0,
            "description": "A burst of incredible strength. Deals more damage on next attack",
        },
        "normal" : {
            "name" : "Earthquake",
            "shield" : 0,
            "damage" : 3,
            "attack" : -21,
            "energy" : -26,
            "health" : 0,
            "description": "A complete disaster. Leaves the opponent vulnerable, dealing more damage on next attack",
        },
        "heal" : {
            "name" : "Protodermis tea",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : -16,
            "health" : 12,
            "description": "A warm protodermis tea is a great way to recover",
        },
        "rest" : {
            "name" : "Mining",
            "shield" : 0,
            "damage" : 3,
            "attack" : 0,
            "energy" : 17,
            "health" : 0,
            "description": "What can be better than mining? Replenishes one's power, increasing the damage from next attack",
        },
    },

    "stone" : {
        "mask" : {
            "name" : "Speed of light",
            "shield" : 10,
            "damage" : 6,
            "attack" : 0,
            "energy" : -27,
            "health" : 0,
            "description": "The user moves with unbelievable speed, allowing him to better dodge attacks. Remains of speed after usage also allow to move faster for some time, increasing damage from next attack",
        },
        "normal" : {
            "name" : "Stone peaks",
            "shield" : 0,
            "damage" : 5,
            "attack" : -21,
            "energy" : -24,
            "health" : 0,
            "description": "Casts stone peaks from under opponent. They also restrict opponent's movement, allowing to hit him more on the next attack",
        },
        "heal" : {
            "name" : "Protodermis tea",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : -13,
            "health" : 10,
            "description": "A warm protodermis tea is a great way to recover",
        },
        "rest" : {
            "name" : "Stone ball",
            "shield" : 0,
            "damage" : 3,
            "attack" : 0,
            "energy" : 14,
            "health" : 0,
            "description": "Good old stone ball. Warms up legs, allowing to move faster and deal more damage on next attack",
        },
    },

"air" : {
        "mask" : {
            "name" : "Levitation",
            "shield" : 14,
            "damage" : 0,
            "attack" : 0,
            "energy" : -21,
            "health" : 0,
            "description": "Allows user to levitate over the opponent. Helps dodge attacks, reducing the damage",
        },
        "normal" : {
            "name" : "Tornado",
            "shield" : 3,
            "damage" : 0,
            "attack" : -22,
            "energy" : -29,
            "health" : 0,
            "description": "Swipes opponent away with tornado. Creates an airstream that allows to better dodge attacks, reducing the damage",
        },
        "heal" : {
            "name" : "Protodermis tea",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : -14,
            "health" : 12,
            "description": "A warm protodermis tea is a great way to recover",
        },
        "rest" : {
            "name" : "Kite",
            "shield" : 2,
            "damage" : 0,
            "attack" : 0,
            "energy" : 16,
            "health" : 0,
            "description": "To launch a kite is always a great way to rest",
        },
    },

"ice" : {
        "mask" : {
            "name" : "Eagle eye",
            "shield" : 4,
            "damage" : 6,
            "attack" : 0,
            "energy" : -25,
            "health" : 0,
            "description": "Helps with precision and prediction. Allows to better dodge attacks and hit critical spots, dealing more damage on next attack",
        },
        "normal" : {
            "name" : "Absolute zero",
            "shield" : 2,
            "damage" : 0,
            "attack" : -23,
            "energy" : -28,
            "health" : 0,
            "description": "Casts freezing temperature over the opponent. Also casts an ice shield on user",
        },
        "heal" : {
            "name" : "Protodermis tea",
            "shield" : 0,
            "damage" : 0,
            "attack" : 0,
            "energy" : -13,
            "health" : 11,
            "description": "A warm protodermis tea is a great way to recover",
        },
        "rest" : {
            "name" : "Skiing",
            "shield" : 0,
            "damage" : 2,
            "attack" : 0,
            "energy" : 15,
            "health" : 0,
            "description": "Skiing is favourite ice village's entertainment. Gained speed also helps to deal more damage on next attack",
        },
    }
}